"""Add columns submenus and dishes counts

Revision ID: 0da4a30f2280
Revises: d284d6a03b78
Create Date: 2024-01-29 20:55:06.998052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da4a30f2280'
down_revision: Union[str, None] = 'd284d6a03b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('submenus_count', sa.Integer(), nullable=True))
    op.add_column('menus', sa.Column('dishes_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'dishes_count')
    op.drop_column('menus', 'submenus_count')
    # ### end Alembic commands ###
