"""Change UUID field in submenu and dish models

Revision ID: 72ba0ae75f55
Revises: 5a1e59334385
Create Date: 2024-01-20 09:44:10.922647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ba0ae75f55'
down_revision: Union[str, None] = '5a1e59334385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
