"""Edit submenu and dishes counts in Menu model

Revision ID: 9dc950e23232
Revises: fc70b16554e1
Create Date: 2024-02-02 15:44:30.826269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc950e23232'
down_revision: Union[str, None] = 'fc70b16554e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
