"""Add cascade delete-orphan for submenu, dish in releations

Revision ID: bd146d636fc0
Revises: 061d38b000d9
Create Date: 2024-01-22 09:20:57.435993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd146d636fc0'
down_revision: Union[str, None] = '061d38b000d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
