"""Unique title for submenu

Revision ID: d284d6a03b78
Revises: 4e2a4b9765ec
Create Date: 2024-01-22 11:45:04.398498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd284d6a03b78'
down_revision: Union[str, None] = '4e2a4b9765ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'submenus', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submenus', type_='unique')
    # ### end Alembic commands ###
