"""Remove sumenus and dishes count from menu model

Revision ID: fc70b16554e1
Revises: f2866db4151d
Create Date: 2024-02-01 14:24:25.157564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc70b16554e1'
down_revision: Union[str, None] = 'f2866db4151d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
