version: "3.8"

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASS
  web:
    build: .
    restart: always
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --reload"
    network_mode: host
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data:
