version: "3.8"

services:
  ylab_db:
    container_name: ylab_db
    hostname: ylab_db
    image: postgres:15.1-alpine
    restart: "unless-stopped"
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-U",
          "${DB_USER}",
          "-d",
          "${DB_NAME}"
        ]
      interval: 10s
      timeout: 30s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: "unless-stopped"
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    network_mode: host
    depends_on:
      ylab_db:
        condition: service_healthy

volumes:
  postgres_data:
