version: "3.8"

services:
  ylab_db_test:
    container_name: ylab_db_test
    image: postgres:15.1-alpine
    restart: "unless-stopped"
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test_db_username
      - POSTGRES_DB=test_db_name
      - POSTGRES_PASSWORD=test_db_user_password
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-U",
          "${DB_USER}",
          "-d",
          "${DB_NAME}"
        ]

  backend_test:
    build:
      context: .
    container_name: backend_test
    restart: "unless-stopped"
    command: ["pytest", "-v", "-s"]
    volumes:
      - .:/app
    network_mode: host
    ports:
      - 8000:8000
    depends_on:
      ylab_db_test:
        condition: service_healthy

volumes:
  postgres_data:
