version: "3.8"

services:
  test_db:
    container_name: test_db
    hostname: test_db
    image: postgres:15.1-alpine
    restart: "unless-stopped"
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_DB=${TEST_DB_NAME}
      - POSTGRES_PASSWORD=${TEST_DB_PASS}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-U",
          "${TEST_DB_USER}",
          "-d",
          "${TEST_DB_NAME}"
        ]
      interval: 10s
      timeout: 30s
      retries: 5

  backend_test:
    build:
      context: .
    container_name: backend_test
    command: ["pytest", "-v"]
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      test_db:
        condition: service_healthy

volumes:
  postgres_data:
